### ISSUE TITLE
Change the reviewer notes red color to red and green colors

### ISSUE THREAD

**Issue by Gonzom** [PythonFreeCourse/lms#103]
Adding a suggestion that was posted on the forum.

Change the reviewer notes red color to red and green. The red one will be for "error"/"fix it" notes, and a green one for good notes. With the drop-down list of preset notes, these can already be predefined as red or green.

**Comment by yammesicka** [comment]
This is a specific use case of issue #72.
It's not an easy task, and unfortunately we have lots of other things to deal with right now.
I hope I'll have some time to implement #72 during June.
