### ISSUE TITLE
'str' object has no attribute 'hex' on full setup

### ISSUE THREAD

**Issue by TomGranot** [PythonFreeCourse/lms#148]
Following the [Full Setup instructions](https://github.com/PythonFreeCourse/lms#full-setup) from the repo's main README, and after running:

```bash
echo "SECRET_KEY = \"$(python -c 'import os;print(os.urandom(32).hex())')\"" >> lms/lmsweb/config.py
```

I'm getting:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'str' object has no attribute 'hex'
```

Not a Pythonista, please excuse if this is kid-level stuff, I'm just debugging by writing this down.

I'm told Python versions matter, and so I'm running (on an AWS EC2 instance):

```
Python 2.7.17 [GCC 7.5.0] on linux2
```
Which implies CPython, I suppose (but that's just me twiddling my thumbs in the air now).

Anywho, looking at the docs for `os.urandom(32)` for Python 2.7.18 [here](https://docs.python.org/2/library/os.html#os.urandom) implies that i should be getting 32 bytes of random data when running that function, and indeed I do when I try to do that in the REPL:

```
>>> os.urandom(32)
'\x9e\xf70FV\xd3m=4!2\xad\x7f\xcaD-\\\xf5"7\xb6\x9cp8\x88\xf0\x9dx\xf6\xa1\xd0\xd6'
```

However, chaining `hex()` to the function makes Python not happy:

```
>>> os.urandom(32).hex()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'str' object has no attribute 'hex'
```

I assume the reason why we're using `os.urandom()` instead of using `uuid.uuid4()` or one of the other `uuid` variants has to do with providing a secret key that is cryptographically secure? 

Didn't open a PR yet since I wasn't sure whether that's needed, and also I could be missing something basic. 

@gal432 I think that's your area, correct?

BTW - actual `SECRET_KEY` line with `uuid` instead of `urandom`:

```bash
echo "SECRET_KEY = \"$(python -c 'import uuid;print(uuid.uuid4().hex)')\"" >> lms/lmsweb/config.py
```

**Comment by yammesicka** [comment]
We use Python 3, in which `os.urandom` returns `bytes` object that have the attribute `hex`.

Please config your default Python to Python 3.

Meanwhile, you can probably run: `echo "SECRET_KEY = \"$(python3 -c 'import os;print(os.urandom(32).hex())')\"" >> lms/lmsweb/config.py`

**Comment by TomGranot** [comment]
@yammesicka Must've missed that. Used the Python on the path which was 2.7.

Thanks a bunch!
