### ISSUE TITLE
Configuration migration expects configuration example existence

### ISSUE THREAD

**Issue by ron-huberfeld** [PythonFreeCourse/lms#178]
Web configuration migration process expects file `lms/lmsweb/config.py.example` while readme instruction will remove this file by - 
`mv lms/lmsweb/config.py.example lms/lmsweb/config.py`

**Comment by yammesicka** [comment]
Yup, that's absolutely a bug.
I see you've addressed it in #179, but that's actually not the way I want to solve it.

Check what causes the program to crush and solve it methodically, please :)

**Comment by yammesicka** [comment]
Your solution was correct, after all ^^"

@Liad-n took the time to explain me why. It's now fixed, thank you both for the effort.
