### ISSUE TITLE
Bug: Can't see comments on exercises

### ISSUE THREAD

**Issue by yammesicka** [PythonFreeCourse/lms#180]

**Comment by ron-huberfeld** [comment]
Can I assist in this?

**Comment by yammesicka** [comment]
I'm super busy and I'll get to solve it in the afternoon.
If you can win this without my help - go ahead :)

**Comment by ron-huberfeld** [comment]
I just need to have a failing example to reproduce the issue :)
I don't have access to other people exercises.
