### ISSUE TITLE
Fix bug displaying SVG files

### ISSUE THREAD

**Issue by yammesicka** [PythonFreeCourse/lms#258]
* [ ] Fix bug
* [ ] Add an appropriate test case

To reproduce:
https://cdn.jsdelivr.net/npm/@icon/hawcons-filled@1.0.0-alpha.3/hawcons-filled.svg

**Comment by ron-huberfeld** [comment]
@yammesicka - please assign to me to have a look

**Comment by ron-huberfeld** [comment]
@yammesicka - I believe you can close this too - right?

**Comment by yammesicka** [comment]
Yup
