### ISSUE TITLE
create course interface

### ISSUE THREAD

**Issue by chenhaoenen** [PythonFreeCourse/lms#359]
Is this project not yet developed? I found that many interfaces have not been implemented

**Comment by yammesicka** [comment]
Hi,

What do you mean by that? What is missing? :)

**Comment by chenhaoenen** [comment]
Thank you for your reply. I use the docker build project. I found that there is no corresponding interface implementation. Only the corresponding functions are included in the lmstests file. For example, teachers create courses, etc., and the front-end page cannot be directly operated

**Comment by yammesicka** [comment]
Oh, I see what you mean. Yeah, there are no glossy front-end implementations for many features.
You can add the resources using the GUI in `/admin` :)

**Comment by chenhaoenen** [comment]
ok, thx
