### ISSUE TITLE
Fix buttons view on mobiles

### ISSUE THREAD

**Issue by yammesicka** [PythonFreeCourse/lms#38]

**Comment by ron-huberfeld** [comment]
@yammesicka please assign to me 
I fixed it

**Comment by yammesicka** [comment]
Currently this is only a partial fix - I would prefer using a @media query that hides the exercise id, the notebook id and the number of errors, leaving only the exercise name (maybe with a smaller font) and the button.

**Comment by yammesicka** [comment]
Fixed by @ron-huberfeld.
