### ISSUE TITLE
Create a better documentation for local environment setup

### ISSUE THREAD

**Issue by yammesicka** [PythonFreeCourse/lms#39]

**Comment by yammesicka** [comment]
@gal432 - I know it's huge PITA, but can you take care about this one?

**Comment by ron-huberfeld** [comment]
@yammesicka - is this issue still open? If yes, do you see this something newbie can do while setting up his own environment?
By the way, I see docker file but no docker-compose - can i add that? (one stop-shop for environment creation?)

**Comment by yammesicka** [comment]
This is indeed still open.

We do have docker-compose [here](https://github.com/PythonFreeCourse/lms/blob/master/devops/lms.yaml), take your time to read the repo before you begin :) 

If you feel familiar with Docker, this issue might be a great one to start with.

**Comment by ron-huberfeld** [comment]
@yammesicka can you assign this issue to me?
