### ISSUE TITLE
Fix old version preventing to reupload an exercise

### ISSUE THREAD

**Issue by yammesicka** [PythonFreeCourse/lms#50]
## Scenario:

1. User uploads a solution to an exercise (A).
2. User mistakenly reuploads another solution to the same exercise (B)
3. User tries to fix his error and to re-upload solution A.
4. LMS stops the upload because the solution is already exists in the DB.

## Solution:
Check de-duplications only with the latest uploaded version.

**Comment by gal432** [comment]
I'm not sure what we want to do here. we wanted to block users to re-upload the same exercise over and over again. what were the reasons? doesn't it get conflicted with letting the users re-upload something that we already have seen?

**Comment by yammesicka** [comment]
The intention was to prevent students from trying to create a new submission of exercise 16, when exercise 15 is on the same notebook and marked as `# Upload 15`. This could make checked exercises go unchecked just because the user unintentionally left the `# Upload 15` comment on the previous exercise.

**Comment by itamargran** [comment]
I'll take this one.

**Comment by yammesicka** [comment]
Fixed by @itamargran in PR #229
