### ISSUE TITLE
Comment saved and appears twice

### ISSUE THREAD

**Issue by IdoElk** [PythonFreeCourse/lms#51]
![image](https://user-images.githubusercontent.com/49623595/79003830-1489bc00-7b5c-11ea-9230-9a0c40a6667e.png)

Notice that it created two comments, one automatic and one of the actual commenter.

![image](https://user-images.githubusercontent.com/49623595/79003849-22d7d800-7b5c-11ea-8560-4f817b248c43.png)

solution ID from images: 22660

**Comment by gal432** [comment]
I think I found the problem. I didn't call the right task on done_checking route

**Comment by yammesicka** [comment]
@gal432 ; can you please issue a PR?

**Comment by gal432** [comment]
Not so much because I committed this directly to master. but let's follow if it happens again.

**Comment by yammesicka** [comment]
Marking as "solved" for now
