### ISSUE TITLE
When resizing the window to about half size, all 4 buttons (log out, archives, upload and notifications) disappear

### ISSUE THREAD

**Issue by Gonzom** [PythonFreeCourse/lms#91]
When resizing the window to about half size, all 4 buttons (log out, archives, upload and notifications) disappear.

This is an actual issue, as I tend to use side-by-side windows so this prevents me from accessing needed buttons.

Expected: still show or converted to a drop down button, but still accessible.

**Comment by yammesicka** [comment]
Solved by #93
